# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b34f8412336ca96f2d6abcf181107b487aa7b5b77819158f48febc06307fe7f0f79744167c90dd097b2f625b56a1e333ba7eec1f6ff56a13c64dab3b4baa7949

test:
  secret_key_base: 0fb6b0cd9825cb6a291dc5d3a804aaf5770a5f5fb8e3f3a7c0ab12e7c0b39744b1e66c4323ddb5aa5988f755ea1c22b458fa6f222ac173f4d4ea0251575b2d6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
